---
title: "Report_draft1"
author: "Kieran Fox"
date: "22/02/2021"
output: html_document
---


```{r setup, echo=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
setwd('C:/Users/kiera/Work/NE_work')
source('./data_prep_figure4.R')
```

```{r import, include=FALSE}
name_gl <- get_names('rename_habitat.csv')
name_swap_vector <- name_gl[[1]]
bb_list <- name_gl[[2]]
bp_list <- name_gl[[3]]

df_all <- read_all_data('all_plots.csv')
# Taking the data from just one site
df_site <- filter(df_all, SITECODE == 'B14') %>%
  fix_names(.) %>%
# transform the eastings and northings into latitude and longitude
  transform_coords(.)

# Making the sub dataframes with only the major habitats selected
#object[[1]] is the data frame. object[[2]] is the list of habitats
df_site.bb <- select_by('BAP_BROAD', 20)
df_site.bp <- select_by('BAP_PRIORITY', 15)
df_site.nvcb <- select_by('NVC_groupb', 15)
df_site.nvcc <- select_by('NVC_groupc', 15)

# the centre points of the maps
east_cent <- get_centre_coords(df_site)[[1]]
north_cent <- get_centre_coords(df_site)[[2]]

unique_years <- unique(df_site$YEAR)
unique_habs <- unique(df_site$BAP_BROAD)
unique_nvchabs <- unique(df_site$NVC_groupc)

total_change <- get_change_by_year(df_site)
```

# Habitats

### BAP broad habitats on the site

```{r Bap_habitat}
map_hab_by_year(df_site, 'BAP_BROAD')
```

### NVC habitats by BAP broad categorisation

```{r NVC_habitats}
map_habitats(df_site)
```

### NVC habitat sub groups

```{r NVC_subgroups}
habitat_by_habitat('NVC_groupc', 'NVC_groupb')
```

# Last year's species richness and diversity

```{r div_rich_map}
int_map_feat_by_hab(df_site, c('Species_richness', 'Species_diversity'))
```

### Species richness

###### Average change over the years

```{r av_change_spec_rich}
plot_feat_by_hab_year('BAP_BROAD', 'Species_richness')
```

###### Map of change

```{r map_change_spec_rich}
#MAP OF CHANGE
```

### Species diversity

###### Average change over the years

```{r av_change_spec_div}
plot_feat_by_hab_year('BAP_BROAD', 'Species_diversity')
```

###### Map of change

```{r map_change_spec_rich}
#MAP OF CHANGE
```

